### ISSUE TITLE
File name filtering

### ISSUE THREAD

**Issue by RyantHults** [Lunatrius/hb-dl#3]
I'm trying to get this script (using -d) to filter results to only specific filetypes. At the moment, it seems this is only searching a list of product names, rather than a list of filenames. Would it be possible to change this or make it an option?

**Comment by Lunatrius** [comment]
I'll look into it.

**Comment by Lunatrius** [comment]
Implemented in 2f01f41a48d8bed5520fd25bcbc9e10fc0df0044 with the `-n`/`--filename` switches. Let me know if it works for you.
