### ISSUE TITLE
hb-dl cannot open humble bundle library

### ISSUE THREAD

**Issue by shakeyourbunny** [Lunatrius/hb-dl#4]
After logging in (replace fake credentials with real ones), the script cannot read the keys...

```
 ./hbdl.py -r
Opening /home...
Trying to log in...
Username [xxxx]: xxxx@example.com
Password:
Password (retype):
Re-opening /home...
Did not land on /home, stopping!
  https://www.humblebundle.com/login?goto=%2Fhome
Traceback (most recent call last):
  File "./hbdl.py", line 542, in <module>
    main()
  File "./hbdl.py", line 507, in main
    products = [data['products'][key] for key in data['products']]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by Lunatrius** [comment]
Are you sure that you entered the correct username and password?

The script will now go back to the login page if the login attempt has failed (aab3c29d131f1d822165cfbfa3fbe87217a57c21).

**Comment by shakeyourbunny** [comment]
I tried typing in the password manually and copied several times from the clipboard (checking no additional spaces etc), it always produces this result.

I think it is related to the Google ReCaptcha, it does not even get to the HumbleGuard.

**Comment by shakeyourbunny** [comment]
Addendum:
It would be neat to be able to skip over the login with a Netscape / wget - style cookie file where all things login are already handled ( username / password / hbguard / google recaptcha), like hbdl.py --cookiefile=path/to/cookie.txt

sample (cookie values removed / censored):

.humblebundle.com       TRUE    /       FALSE   1495288068      _gat    1
.humblebundle.com       TRUE    /       FALSE   1495374445      _gid    xxxxx
.humblebundle.com       TRUE    /       FALSE   1526823789      __cfduid     xxxxx   
.humblebundle.com       TRUE    /       FALSE   1558360045      _ga     xxxx
.humblebundle.com       TRUE    /       FALSE   1896130800      __ssid  xxxx
www.humblebundle.com    FALSE   /       FALSE   0       hbflash None
www.humblebundle.com    FALSE   /       FALSE   0       hbreqsec        True
www.humblebundle.com    FALSE   /       FALSE   1495288606      hbguard-email   emailed
www.humblebundle.com    FALSE   /       FALSE   1497917530      xxxxxxx
www.humblebundle.com    FALSE   /       FALSE   1526823790      csrf_cookie    xxxxx
www.humblebundle.com    FALSE   /       FALSE   1810648044      hbguard "xxxxxxx"
www.humblebundle.com    FALSE   /       FALSE   1911844800      pnctest 1
www.humblebundle.com    FALSE   /       TRUE    1558359842      _simpleauth_sess        "xxxxx"

**Comment by Lunatrius** [comment]
Try replacing the `LWPCookieJar` class with `MozillaCookieJar` [here](https://github.com/Lunatrius/hb-dl/blob/aab3c29d131f1d822165cfbfa3fbe87217a57c21/hbdl.py#L102). It should load the cookies.

https://docs.python.org/3.3/library/http.cookiejar.html?highlight=cookie#filecookiejar-subclasses-and-co-operation-with-web-browsers
